# Generated by Django 3.0.8 on 2020-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbtzmenarenapp', '0008_buy_btc_buy_ltc_sell_btc_sell_ltc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('btc', models.DecimalField(decimal_places=8, max_digits=11)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_eur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.CharField(max_length=10)),
                ('eur', models.DecimalField(decimal_places=2, max_digits=9)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_ltc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('ltc', models.DecimalField(decimal_places=8, max_digits=14)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
