# Generated by Django 3.0.8 on 2020-07-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xbtzmenarenapp', '0010_auto_20200721_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_sell_ltc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltc', models.DecimalField(decimal_places=8, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_sell_btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.DecimalField(decimal_places=8, max_digits=11)),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_buy_ltc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltc', models.DecimalField(decimal_places=8, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_buy_btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.DecimalField(decimal_places=8, max_digits=11)),
                ('price', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
