# Generated by Django 3.0.8 on 2020-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbtzmenarenapp', '0017_auto_20201213_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eth',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
