# Generated by Django 3.0.8 on 2020-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbtzmenarenapp', '0019_auto_20201215_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='xlm',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zrx',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
